### PR TITLE
Yohannes Homework Java Script week4

### PR DESCRIPTION
**Pull request by byohannes**

### CODE REVIEW

**Comment by ChrisOwen101** [comment]
Is this the homework from Week 4? Looks like you've included an exercise from Week 1 by mistake

**Comment by byohannes** [comment]
> Is this the homework from Week 4? Looks like you've included an exercise from Week 1 by mistake

Ohh Yes, Chris, this is for week 4, But an exercise from week 1 keep coming every week  could you pls give a hint on how to resolve this mistake and thanks 

> Is this the homework from Week 4? Looks like you've included an exercise from Week 1 by mistake

**Comment by byohannes** [comment]
> Is this the homework from Week 4? Looks like you've included an exercise from Week 1 by mistake

**Comment by byohannes** [comment]
> > Is this the homework from Week 4? Looks like you've included an exercise from Week 1 by mistake
> 
> Ohh Yes, Chris, this is for week 4, But an exercise from week 1 keep coming every week could you pls give a hint on how to resolve this mistake and thanks
> 
> > Is this the homework from Week 4? Looks like you've included an exercise from Week 1 by mistake

Hi Chris, I have resolved the previous issue by deleting the file but unfortunately I have closed the PR, could you please open it for review pls.
thanks.

**Pull request closed without merging**
